### PR TITLE
fix: make connector respect server-side max allowed range length

### PR DESCRIPTION
**Pull request by vursen**
## Description

There is a [server-side limitation](https://github.com/vaadin/flow/blob/6124a96af94be10cdb5749aa3384daa47003ed62/flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java#L332-L339) on how big the requested items range can be which equals 10 * pageSize. This PR ensures the ComboBox connector doesn't request ranges of а size exceeding 10 * pageSize to prevent exceptions and thus endless loading.

Fixes https://github.com/vaadin/flow-components/issues/3715

## Type of change

- [x] Bugfix

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/contributing/overview
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

**Review by ugur-vaadin — APPROVED** [review]

**Comment by tomivirkki** [comment]
Would fixing https://github.com/vaadin/flow/issues/14630 help in this case?

**Comment by vursen** [comment]
> Edit: it would fix the issue in case the minimum is set to 500 items / request because that's also the current minimum active range length in the combobox connector

Right, it would be a more proper fix but we can keep a tests improvement part from this PR

**Comment by vursen** [comment]
Extracted test improvements into https://github.com/vaadin/flow-components/pull/3799.

**Comment by vursen** [comment]
Now that the test improvements part has got to `master` as part of #3799, I'm closing this PR.

**Pull request closed without merging**
