### PR TITLE
feat: Add scrollTo API to VirtualList

### LINKED ISSUE #4450: Add scrollTo API for VirtualList
### Describe your motivation

Grid has the API, the web component has the API. 

### Describe the solution you'd like

The same API as Grid.

### Describe alternatives you've considered

Doing it in user space, but it's not helpful for anyone except me. 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by marcushellberg**
## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes #4450

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/contributing/overview
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

----
I have tested the changes locally, but don't know how to create tests, will need help with that.

### CODE REVIEW

**Comment by oliveryasuna** [comment]
Originated here: https://discord.com/channels/732335336448852018/1056236745261330472.

Thanks @marcushellberg for handling this!

**Review by samie — APPROVED** [review]
LGTM.

Further improvement: There could be index bound checks before calling JS.

**Comment by sissbruecker** [comment]
If this is still relevant, please reopen the PR against `main` and add integration tests as per the contribution guidelines.

**Comment by samie** [comment]
Is there a API or why wouldn't it be relevant? If you could provide some links to similar tests you wish to have here?

**Comment by sissbruecker** [comment]
That was just another way of checking if there is still interest in continuing with this contribution. A similar integration test for Grid can be found here: https://github.com/vaadin/flow-components/blob/d269bea2231f713e7f8684c00c2d3e82d8da3f12/vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridScrollToIT.java

**Comment by marcushellberg** [comment]
I would still like to get this merged into the product, but I'll need some help with the test. I don't have enough time right now to figure out the testing. Can we either: 

1. Set up a 30 min screen share session to get it done, or
2. Have someone from the team with more knowledge help create the needed test

Thanks.

**Comment by sissbruecker** [comment]
Opened https://github.com/vaadin/flow-components/pull/5037 instead

**Pull request closed without merging**
