### PR TITLE
chore: apply formatter:format to java code

### PR DESCRIPTION
**Pull request by manolo**
This PR contains only formatting changes, after applying `mvn formatter:format` plugin with the flow configuration

### CODE REVIEW

**Review by ZheSun88 — APPROVED** [review]

**Comment by manolo** [comment]
TestComment

**Comment by manolo** [comment]
15:16 - 27-Apr

This is a comment from TC

**Comment by manolo** [comment]
${CONTENT}

**Comment by manolo** [comment]
17:16 - 27-Apr

This is a comment from TC

**Comment by manolo** [comment]
\n\n19:51 - 27-Apr\n\nThis is a comment from TC\n\n

**Comment by manolo** [comment]
Hello all

**Comment by manolo** [comment]
Hello all

**Pull request merged**
