### PR TITLE
fix: remove old license-checker from spreadsheet

### PR DESCRIPTION
**Pull request by tomivirkki**

### CODE REVIEW

**Review by web-padawan — APPROVED** [review]

**Comment by Artur-** [comment]
How is this "old"?

**Comment by tomivirkki** [comment]
> How is this "old"?

None of the other commercial components have it even though the client-side license-checking was removed from them. But the real problem here seems to be that the check is `if (service.getDeploymentConfiguration().isProductionMode()) {` while it should be `if (!service.getDeploymentConfiguration().isProductionMode()) {`

**Comment by Artur-** [comment]
The web component license checking that has explicit calls is old. This is not in any way old

**Comment by tomivirkki** [comment]
> This is not in any way old

Should the same check then be added to the other Commerical Flow components?

**Comment by Artur-** [comment]
Yes, to all those which do not have a web component on the client side

**Comment by web-padawan** [comment]
> Yes, to all those which do not have a web component on the client side

Spreadsheet is the only one. Other Pro components are covered by `static get cvdlName()` in JS.

**Comment by tomivirkki** [comment]
Closing in favour of https://github.com/vaadin/flow-components/pull/4255

**Comment by tomivirkki** [comment]
Techincally Spreadsheet also has a Web Component. Could we drop this check if we added the following to [`vaadin-spreadsheet.js`](https://github.com/vaadin/flow-components/blob/master/vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/vaadin-spreadsheet.js)?

```js
static get cvdlName() {
  return 'vaadin-spreadsheet';
}
```

**Comment by Artur-** [comment]
It needs to be installed as an npm package also

**Pull request closed without merging**
