### PR TITLE
doc: update documentation with formatting conventions [skip ci]

### PR DESCRIPTION
**Pull request by manolo**

### CODE REVIEW

**Review by ZheSun88 — APPROVED** [review]

**Comment by manolo** [comment]
08:10 - 28 - Apr     ![BLOCKER][BLOCKER] There are  files with format errors     Please run `mvn formatter:format` in your branch and commit the changes.These are the differences in your PR:lorem

**Comment by manolo** [comment]
10:23 - 28 - Apr     ![BLOCKER][BLOCKER] There are  files with format errors     Please run `mvn formatter:format` in your branch and commit the changes.These are the differences in your PR:lorem

**Comment by manolo** [comment]
12:11 - 28 - Apr


     ![BLOCKER][BLOCKER] There are  files with format errors

     Please run `mvn formatter:format` in your branch and commit the changes.

These are the differences in your PR:

**Comment by manolo** [comment]
12:11 - 28 - Apr


     ![BLOCKER][BLOCKER] There are  files with format errors

     Please run `mvn formatter:format` in your branch and commit the changes.

These are the differences in your PR:

**Comment by manolo** [comment]
12:11 - 28 - Apr


![BLOCKER][BLOCKER] There are  files with format errors

Please run `mvn formatter:format` in your branch and commit the changes.

These are the differences in your PR:

**Comment by manolo** [comment]
12:15 - 28 - Apr


![BLOCKER][BLOCKER] There are  files with format errors

Please run `mvn formatter:format` in your branch and commit the changes.

These are the differences in your PR:

     

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'

**Pull request merged**
