### PR TITLE
fix: Use English when converting code properties to lower case

### LINKED ISSUE #2715: Lowercase localization problem on Turkish in SplitLayout
### Description of the bug

When I set orientation VERTICAL or HORIZONTAL, in default(English) it converted to `vertical` or `horizontal`. But when locale set to Turkish it converted to `vertıcal`,` horızontal`. 
vaadin-tr-bug

### Expected behavior

It should be lowercased by English _not with system default_

### Minimal reproducible example

```
// In application startup 

Locale trLocale = Locale.forLanguageTag("tr-TR");
Locale.setDefault(trLocale);

//In some view
SplitLayout splitLayout = new SplitLayout(new Div(), new Div());
splitLayout.setWidth(100, Unit.PERCENTAGE);
splitLayout.setOrientation(SplitLayout.Orientation.VERTICAL);
```

### Versions

- Vaadin / Flow version: 22.0.5
- Java version: 11 
- OS version: MacOS 11.3.1
- Browser version (if applicable): 
- Application Server (if applicable):
- IDE (if applicable):

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #2715

### CODE REVIEW

**Comment by sissbruecker** [comment]
There are a few syntax errors in this PR, and I think we should also add tests. I'm going to take a look at this.

**Comment by Artur-** [comment]
I considered tests but testing the current cases does not provide that much value and I could not figure out how to test for future problems

**Comment by Artur-** [comment]
Now it should compile..

**Comment by sissbruecker** [comment]
> I considered tests but testing the current cases does not provide that much value and I could not figure out how to test for future problems

Yeah I looked into this a bit, we could run tests on all supported locales, but that seems a bit out of proportion for this problem. Let's skip this for now.

**Review by sissbruecker — APPROVED** [review]

**Pull request merged**
