### PR TITLE
chore: Add dtrack-maven-plugin configuration for SCA

### PR DESCRIPTION
**Pull request by fluorumlabs**

### CODE REVIEW

**Comment by sissbruecker** [comment]
@fluorumlabs Can you please provide some context what this is supposed to achieve? There is neither a ticket, nor a description.

**Comment by fluorumlabs** [comment]
@sissbruecker This will allow to generate software bills of materials (SBOM) and upload to Vaadin OWASP Dependency-Track instance to perform Software Composition Analysis (SCA)

**Comment by web-padawan** [comment]
There is a similar PR merged to Flow repo recently: https://github.com/vaadin/flow/pull/11656

**Review by sissbruecker — APPROVED** [review]
OK then

**Pull request merged**
