### PR TITLE
chore: update flow version to 8.0 on master branch

### PR DESCRIPTION
**Pull request by ZheSun88**

### CODE REVIEW

**Comment by stbischof** [comment]
@maho7791 could you please verify this?

AFAIK the latest release of components like the `vaadin-button-flow` is version `19.0.6` 
https://mvnrepository.com/artifact/com.vaadin/vaadin-button-flow

This is the manifest
```
Manifest-Version: 1.0
Implementation-Title: Vaadin Button
Bundle-License: http://www.apache.org/licenses/LICENSE-2.0
Bundle-SymbolicName: com.vaadin.flow.component.button
Archiver-Version: Plexus Archiver
Built-By: 
Bnd-LastModified: 1619423343101
Bundle-ManifestVersion: 2
Import-Package: com.vaadin.flow.component;version="[6.0,7)",com.vaadin
 .flow.component.dependency;version="[6.0,7)",com.vaadin.flow.componen
 t.page;version="[6.0,7)",com.vaadin.flow.dom;version="[6.0,7)",com.va
 adin.flow.function;version="[6.0,7)",com.vaadin.flow.internal;version
 ="[6.0,7)",com.vaadin.flow.internal.nodefeature;version="[6.0,7)",com
 .vaadin.flow.shared;version="[6.0,7)"
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-4.1.0.201810181252
Export-Package: com.vaadin.flow.component.button;uses:="com.vaadin.flo
 w.component,com.vaadin.flow.component.dependency";version="19.0.6"
Bundle-Name: vaadin-button-flow
Bundle-Version: 19.0.6
Vaadin-Package-Version: 1
Created-By: Apache Maven Bundle Plugin
Build-Jdk: 1.8.0_201
```
when you are now switching to `<flow.version>8.0-SNAPSHOT</flow.version>` the release will have a manifest like 
```
Import-Package: com.vaadin.flow.component;version="[8.0,9)",
```
Then will no component (here button) bundle be available that could resolve with the  `com.vaadin.flow.component;version=7`

**Comment by maho7791** [comment]
I agree with @stbischof.
Because flow itself and the components are separated, in OSGi you should take care, that the components like button fit in the version range of your flow.
In case of Stefans example I would probably go for: 
`Import-Package: com.vaadin.flow.component;version="[6.0,9)",`

**Comment by stbischof** [comment]
>> In case of Stefans example I would probably go for:
Import-Package: com.vaadin.flow.component;version="[6.0,9)"


But just if the api allowes this range

**Review by manolo — APPROVED** [review]

**Comment by manolo** [comment]
@stbischof just fyi, we have latest pre-releases  in https://tools.vaadin.com/nexus/content/repositories/vaadin-prereleases/com/vaadin/vaadin-button-flow/, there we have 20.0.0.alpha8, and 21.0-SNAPSHOT

**Pull request merged**
