### PR TITLE
feat: remove FooterRow from Grid

### PR DESCRIPTION
**Pull request by benno-mueller-saxess**
Added a method to remove footer rows in order to display dynamic contents in footer rows.

Web-component: vaadin-grid
Related-to: migrated from https://github.com/vaadin/vaadin-grid-flow/pull/951

### CODE REVIEW

**Comment by StefanPenndorf** [comment]
This pull request adresses https://github.com/vaadin/vaadin-grid/issues/1865

Any chance this get's merged-in?

**Comment by yuriy-fix** [comment]
Dear @StefanPenndorf ,
Thank you for your contribution!

Unfortunately, PR cannot be merged as is. Firstly, we need to consider removing rows one by one and not all at the same time. In addition we need to make sure the functionality is also implemented for `headerRow`, make sure all of the new API is tested with current `columnLayer` implementation and features (add unit and integration tests) and align the docs with existing API.

**Comment by manolo** [comment]
Please rebase this branch after [format changes in master](https://github.com/vaadin/flow-components/pull/845), I cannot do since this is in your personal account

**Comment by yuriy-fix** [comment]
Closing as stale.

**Pull request closed without merging**
