### PR TITLE
feat: add scrollTo API to VirtualList

### PR DESCRIPTION
**Pull request by sissbruecker**
## Description

Adapted from https://github.com/vaadin/flow-components/pull/4451

Cherry-picked to `main` and added integration tests.

Closes https://github.com/vaadin/flow-components/issues/4450

Depends on https://github.com/vaadin/web-components/pull/6588

## Type of change

- Feature

### CODE REVIEW

**Comment by sissbruecker** [comment]
Scrolling to an index immediately after adding the component does not work properly:
```java
VirtualList<String> virtualList = new VirtualList<>();
virtualList.setItems(IntStream.rangeClosed(0, 1000).mapToObj(String::valueOf));
virtualList.scrollToIndex(500);
```
The component only scrolls to somewhere in the vicinity of the index (index `536` from my testing).

**Review by ugur-vaadin — DISMISSED** [review]

**Comment by mrgreywater** [comment]
As a dirty workaround for it not scrolling perfectly to elements that are out of view, I changed it to
```java
public void scrollToIndex(int rowIndex) {
        getElement().executeJs("this.scrollToIndex($0); setTimeout(() => this.scrollToIndex($0), 100); setTimeout(() => this.scrollToIndex($0), 300);", rowIndex);
}
```

But I assume the proper place to really fix this is in the underlying web-component, in particular the iron-list-adapter.js.

**Comment by sissbruecker** [comment]
Yeah, I think we should check if a proper fix in the web component is possible. Marked as draft for now until we have some time to go over it.

**Comment by tomivirkki** [comment]
I tried to reproduce the mentioned issue with the following view:
```java
VirtualList<String> virtualList = new VirtualList<>();
add(virtualList);
virtualList.setItems(IntStream.rangeClosed(0, 1000).mapToObj(String::valueOf));
virtualList.scrollToIndex(500);
```

Didn't see any issues on Chrome and Safari:

https://github.com/vaadin/flow-components/assets/1222264/ebec9a8f-2df3-4e41-b402-0685b6253853

on Firefox, the index is a bit off (first visible index ends up being 499).

https://github.com/vaadin/flow-components/assets/1222264/1dca7ff3-ce4f-4492-b65f-665b7ac452f8

**Comment by ugur-vaadin** [comment]
I could not reproduce the "scrolling to an index immediately after adding" issue as well. However, there are some quirks with Firefox scrolling in general. I submitted an [issue](https://github.com/vaadin/flow-components/issues/5538) for a problem I discovered during the investigation. However, this issue was already there before the changes in this PR. Apart from the first item being slightly off like mentioned before, I think this PR is good as it is.

**Comment by tomivirkki** [comment]
@ugur-vaadin I'm currently fixing the issue discovered in the virtualizer https://github.com/vaadin/web-components/pull/6588

I'll update this PR once the Web Component PR is merged

**Review by tomivirkki — APPROVED** [review]

**Pull request merged**
