### PR TITLE
chore: Use global imports for Material

### PR DESCRIPTION
**Pull request by Artur-**
Uses the global JS files for Material (added in https://github.com/vaadin/web-components/pull/5756) so the theme can be loaded at any point in time and styles always end up in the beginning of `<head>`

This is the same as #4808 done for Lumo

### CODE REVIEW

**Comment by Artur-** [comment]
Likely needs a new web component release and update here for tests to pass

**Comment by vursen** [comment]
I rebased the branch from `main`. Let's see if the tests pass.

**Comment by vursen** [comment]
Besides, could you @Artur- please mention in the description what this PR follows up on?

**Comment by Artur-** [comment]
Updated the description. Still needs a new web component release containing https://github.com/vaadin/web-components/pull/5756

**Review by vursen — APPROVED** [review]

**Review by web-padawan — APPROVED** [review]

**Comment by Artur-** [comment]
Weird. This should now pass and locally it works

**Comment by Artur-** [comment]
Ah ok so it's some other problem as #5034 fails in the same way

**Pull request merged**
