### PR TITLE
feat: add missing Inactive property to States

### PR DESCRIPTION
**Pull request by TatuLund**
This property was missing

See Highcharts API spec https://api.highcharts.com/highcharts/series.column.states.inactive

Fixes: https://github.com/vaadin/flow-components/issues/1047

### CODE REVIEW

**Review by alvarezguille — CHANGES_REQUESTED** [review]
This PR includes more API than [officially documented](https://api.highcharts.com/highcharts/plotOptions.series.states.inactive)
And not all of it seems to work [like halo and fillColor in this example](https://jsfiddle.net/alvarezg/bhj8twcm/)
We should have test and some example backing the new API.

**Comment by alvarezguille** [comment]
Apart from the requested changes, this shouldn't be merged until decided if it's going to V22, AC is created and master is for v22.

**Comment by TatuLund** [comment]
Test code

```
public class InactiveViewextends Div {

    public InactiveView() {
        add(new Text("Todays opinnions"));
        
        Chart chart = new Chart(ChartType.PIE);
        DataSeries series = new DataSeries();
        DataSeriesItem item1 = new DataSeriesItem("Yes",50); 
        DataSeriesItem item2 = new DataSeriesItem("No",30); 
        DataSeriesItem item3 = new DataSeriesItem("Don't know",20);
        item3.setSliced(true);        
        series.setData(Arrays.asList(item1,item2,item3));
        chart.getConfiguration().setSeries(series);
        PlotOptionsPie options = new PlotOptionsPie();
        States states = new MyStates();
        Inactive hover = new Inactive();
        hover.setOpacity(1.0);
        SolidColor black = new SolidColor("#000000");
        hover.setBorderColor(black);
        SolidColor color = new SolidColor("#808080");
        hover.setColor(color);
        hover.setBrightness(1);
        hover.setAnimation(false);
        states.setInactive(hover);
        options.setStates(states);
        chart.getConfiguration().setPlotOptions(options);
        add(chart);
    }

```

**Comment by alvarezguille** [comment]
One possible blocker for this feature is that `States` class is also used in `Marker` and `inactive` not going to work there

**Comment by TatuLund** [comment]
> One possible blocker for this feature is that `States` class is also used in `Marker` and `inactive` not going to work there

@alvarezguille I would address limitation this with documentation.

**Review by alvarezguille — APPROVED** [review]

**Review by alvarezguille — APPROVED** [review]

**Pull request merged**
