### PR TITLE
feat: use bnd-maven-plugin for building OSGi (in behalf of @stbischof)

### PR DESCRIPTION
**Pull request by manolo**
Continuation of  reverted [PR](https://github.com/vaadin/flow-components/pull/708) switching from felix to bnd plugin and other fixes proposed in [PR](https://github.com/vaadin/flow-components/pull/780) by @stbischof 
This change also renames packages in demo projects to match pattern `.demo`

There is a bunch of open questions from the author that we should answer before continuing

1. Should all demo projects use the *.demo package (some do, some not)?
2. Should demo jars be osgi-bundles?
3. Why all demo Projects waste time in calculating a OSGi-Manifest IF it is may not needed (?) AND the manifest file not picked up.
4. Should be, building an OSGi-Bundle, only a part of the java-doc profile attach-docs

### CODE REVIEW

**Comment by manolo** [comment]
There are some classes that do not compile and chart tests broken after the refactoring, I'm fixing those to make the PR validation pass

**Comment by manolo** [comment]
Build is green, after couple of fixes.

My opinion about your open questions?

> Should all demo projects use the *.demo package (some do, some not)?

Yes, we should align all demos

> Should demo jars be osgi-bundles?

It does not hurt, we do not have to maintain all pom.xml files in demos since we already have a template for generating them

> Why all demo Projects waste time in calculating a OSGi-Manifest IF it is may not needed (?) AND the manifest file not picked up.

It's not a big deal, it just some milliseconds per component, just in build time.

> Should be, building an OSGi-Bundle, only a part of the java-doc profile attach-docs

makes, sense, but still not a big deal

**Comment by manolo** [comment]
In this ticket, design-system team plan to remove demos, I think we can still accept changes in this PR until demos are removed.
see https://github.com/vaadin/flow-components/issues/193

**Comment by web-padawan** [comment]
I'm ok to accept changes to demos even though they are not published anywhere.

**Review by sissbruecker — APPROVED** [review]
Gave this a check. Apart from the OSGI related changes, which I'm not qualified to comment on and as such accept in good faith considering that nothing breaks, the remaining changes to demos look OK to me. Approved.

**Comment by sissbruecker** [comment]
@manolo Do you see any other effort here, or can we merge this?

**Comment by manolo** [comment]
@sissbruecker  LGTM, go ahead with merge.

**Pull request merged**
