### PR TITLE
Make AppLayout.java "add" method public :)

### PR DESCRIPTION
**Pull request by markvolkov**
## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/contributing/overview
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.
- [x] I have not completed some of the steps above and my pull request can be closed immediately.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by TatuLund** [comment]
I would ask why? This method is private for a reason. There is method AppLayout#setContent which you can use to set the displayed content.

**Comment by sissbruecker** [comment]
>  I have not completed some of the steps above and my pull request can be closed immediately.

Alright

**Comment by markvolkov** [comment]
> I would ask why? This method is private for a reason. There is method AppLayout#setContent which you can use to set the displayed content.



> > I have not completed some of the steps above and my pull request can be closed immediately.
> 
> Alright

That was a mistake on my end was around 1am when I made the PR

**Comment by markvolkov** [comment]
> I would ask why? This method is private for a reason. There is method AppLayout#setContent which you can use to set the displayed content.

@TatuLund setContent does not work. I have tested it out, but it does not have the functionality you think it does. Once you set the content instance field in the setContent() method the add method will no longer render the component. Hence why I would like the add method to be public. I have a legit use-case for it and I will continue to use reflection if I have to.  You can test out setContent if you'd like and let me know if I am doing something wrong. There could be a bug in the AppLayout.class 
 I am using-
        <java.version>17</java.version>
        <vaadin.version>24.0.5</vaadin.version>
Best Regards,
Mark Volkov

**Comment by markvolkov** [comment]
I have tried with reflection setting content and then calling add() mimicking the setContent method and the content is never displayed after. However if you add without "this.content = content" or setting the content you want to add in the content instance field the component I want to add renders fine.

**Comment by markvolkov** [comment]
I would appreciate if you guys can re-open this PR and take a look.

Best Regards,
Mark Volkov

**Comment by sissbruecker** [comment]
If you think there is a bug with `AppLayout` then please create an issue with a reproduction. From a quick glance the [documentation examples](https://vaadin.com/docs/latest/components/app-layout/#auto-height) seem to be working fine, so there must be something specific to your use-case. 

Apart from "setContent probably has a bug" there is also no case to proceed with this PR. If there's a bug in the intended mechanism to add content, then that should be fixed rather than adding something new. If you want to make a case for users being able to use a different method for adding content, then please file an enhancement issue first.

**Comment by TatuLund** [comment]
@markvolkov I would recommend to open an issue ticket first with detailed description of the intended use case.

Idea of AppLayout is to work as RouterLayout. That is why setContent is implemented in the way it is. And when used as RouterLayout, upon navigation, the navigation target component is set using setContent.

**Pull request closed without merging**
