### PR TITLE
chore: overload constructor in order not to break API

### PR DESCRIPTION
**Pull request by manolo**
fixes: https://github.com/vaadin/flow-components/issues/6221

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
Wouldn't this partially fix #6221?
The protected method `Upload#fireUpdateProgress(long, long)` is still missing.

**Comment by manolo** [comment]
@DiegoCardoso updated

**Comment by DiegoCardoso** [comment]
I just noticed that the constructor of `ProgressUpdatEvent` has been also changed too on the same PR:

```diff
public ProgressUpdateEvent(Upload source, long readBytes,
-            long contentLength) {
+           long contentLength, String fileName) {
```

Something we have discussed is that while this PR fixes the binary compatibility of the classes, it still breaks the behavior of anyone who currently extends `Upload` and overrides the `fireUpdateProgress` protected method. We need to ensure that this behavioral change is mentioned in the release notes.

**Comment by manolo** [comment]
Can you explain the problem with an example?

**Comment by DiegoCardoso** [comment]
If someone creates a class like

```java
class MyUpload extends Upload {
	protected void fireUpdateProgress(long totalBytes, long contentLength) {
		super(totalBytes, contentLength);
		// some custom logic
	}
}
```

Before, that method would be called from `DefaultStreamVariable#onProgress` method, but now as the new `fireUpdateProgress` containing the `fileName` parameter is called instead, the old method with two arguments will not be called anymore, so anyone relying on that would see a difference in behavior.

**Comment by manolo** [comment]
Then if this is need to be documented, probably it's better just mention in the release notes the change and not overload any method. Still is an API change in a minor. DS team should decide what's the best option then

**Review by DiegoCardoso — APPROVED** [review]

**Pull request merged**
