### PR TITLE
feat: add missing ItemLabelGenerator to the radiobuttongroup

### PR DESCRIPTION
**Pull request by jcgueriaud1**
## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes https://github.com/vaadin/flow-components/issues/1681

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs-beta/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

I have updated the current test that is using a setRenderer(new TextRenderer()) since this is doing the same and setRenderer is already tested in the other tests with a Component renderer.

### CODE REVIEW

**Comment by sosa-vaadin** [comment]
Since this is a new feature, an acceptance criteria should be provided in the original issue. We should also make sure these changes comply with said criteria.

**Comment by mvysny** [comment]
> Since this is a new feature, an acceptance criteria should be provided in the original issue. We should also make sure these changes comply with said criteria.

I think the API is rather self-explanatory: have an API that would provide captions for radio buttons. The function is similar to `ComboBox.setItemLabelGenerator()` and others which are already present in Vaadin.

**Comment by jcgueriaud1** [comment]
@sosa-vaadin is it required to create an acceptance criteria? In that case who should do that?
I basically copy/paste the code https://github.com/vaadin/flow-components/blob/master/vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java#L352

to https://github.com/vaadin/flow-components/blob/b85a8e2032fa8a7efcb3f92fd857f5e394fef90c/vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java#L254

So if there is an acceptance criteria for the checkboxgroup, just use this.

**Comment by yuriy-fix** [comment]
The AC ticket is ready: https://github.com/vaadin/platform/issues/2601.

**Pull request merged**
