### PR TITLE
feat: Bump minimum Java version to 11

### PR DESCRIPTION
**Pull request by Artur-**

### CODE REVIEW

**Comment by ZheSun88** [comment]
we will update the script for running the validation for this change

**Comment by manolo** [comment]
It seems that there are also memory-leaks when using jdk-11, should we do the same with flow-maven-plugin parameters than you did in flow build ? 

Take a look to [this](https://teamcity.vaadin.com/buildConfiguration/VaadinFlowComponents_PullRequestValidation?branch=2473&buildTypeTab=overview&mode=builds)

**Comment by ZheSun88** [comment]
it looks the validation has only been run on the grid module.. 

image

**Comment by ZheSun88** [comment]
fixed the script, when there are changes in the root (e.g. pom.xml) and individual component modules  
the build will run validation for the whole project

**Comment by ZheSun88** [comment]
now it looks more reasonable. let us run it again, then merge it.

**Review by ZheSun88 — APPROVED** [review]

**Pull request merged**
