### PR TITLE
Issue 992 fix

### LINKED ISSUE #992: Include a private constructor to ChartSerialization.
The [ChartSerialization](https://github.com/vaadin/flow-components/blob/master/vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/util/ChartSerialization.java) class only has static methods available. As such, there is no need to use instances of this class.

I suggest adding a private constructor to avoid creating instances of this class since they would be pretty much useless.

### PR DESCRIPTION
**Pull request by shivansh29**
## Include a private constructor to ChartSerialization

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes #992

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs-beta/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by sosa-vaadin** [comment]
Fixes #992

**Review by sosa-vaadin — CHANGES_REQUESTED** [review]
Please, update your branch with the latest changes from `master` and run the following command:

```sh
mvn formatter:format
```

So the "Run formatter" check passes and we can merge this PR.

**Comment by shivansh29** [comment]
Hey @sosa-vaadin  any hint why is pull request validation failing
I used git pull is shows Already up to date

**Comment by sosa-vaadin** [comment]
I will investigate any issues with our CI server. Once its fixed I will re-run all checks and when they pass, merge your PR.
Thanks for your contribution.

**Comment by ZheSun88** [comment]
Hi @shivansh29 and @sosa-vaadin , i have fixed the PR validation build. sorry for the inconvenience.

**Review by sosa-vaadin — APPROVED** [review]

**Pull request merged**
