### PR TITLE
chore: update flow to 24.3-SNAPSHOT

### PR DESCRIPTION
**Pull request by vursen**
Depends on
- https://github.com/vaadin/flow-components/pull/5724

### CODE REVIEW

**Review by ZheSun88 — APPROVED** [review]

**Comment by ZheSun88** [comment]
i think this error is not  a random failure. 
```
Caused by: java.lang.AssertionError: Error message in browser log: [2023-11-09T13:58:32.139Z] [SEVERE] http://172.16.1.174:8080/VAADIN/build/FlowClient-60ad8908.js 0:4738 Uncaught TypeError: Cannot read properties of undefined (reading 'setDefaultHideDelay')
```

**Comment by vursen** [comment]
The build failures are caused by a regression: https://github.com/vaadin/flow/issues/18016

**Comment by vursen** [comment]
FYI, it wasn't a regression, but a bug in `TooltipConfiguration` that has become visible after Flow enabled logging errors in production.

**Comment by ZheSun88** [comment]
there are still two tests failed 

```
com.vaadin.flow.component.dialog.tests.DialogWithShortcutIT.dialogWithShortcutAndAllowBrowserDefault_containsInput_shortcutDoesNotBlockInput[any_Chrome_]
com.vaadin.flow.component.dialog.tests.DialogWithShortcutIT.dialogWithShortcut_containsInput_shortcutDoesNotBlockInput[any_Chrome_]
```

**Comment by tomivirkki** [comment]
> there are still two tests failed

This seems to be due to some click shortcut related Flow regression.

With the following view:

```java
var button = new Button("Click me");
button.addClickShortcut(Key.KEY_X).setBrowserDefaultAllowed(true);
add(button, new TextField());
```

Before:

https://github.com/vaadin/flow-components/assets/1222264/2380f0ac-1912-4356-bb62-f16ecca475e0

After:

https://github.com/vaadin/flow-components/assets/1222264/19ad5a2b-ed99-4941-b209-36ce68a8773f

For some reason, every second character following a press of the click shortcut key gets cleared.

Related issue: https://github.com/vaadin/flow/issues/10362

**Pull request merged**
