### PR TITLE
use bnd maven plugin for building osgi bundles

### PR DESCRIPTION
**Pull request by stbischof**
This pr switches from felix plugin to newer bnd plugin.

It is a bit hard to build with the build scripts. It would help a lot to understand why you have the different maven profiles. Think there is a lot of optimization possible.

For the momenti tried this the automatic build of PR. 

If i login as guest to the the result i got:

```
404
You do not have enough permissions to access project with internal id: project28

Check that the URL is correct.

Previous page
Overview page
```

So i cant see if the manifest and the resource working properly. I will squash the commits if somebody tells me that is work's or i can see it in the ci

### CODE REVIEW

**Comment by ZheSun88** [comment]
Hi @stbischof , we recently have refactored the `demo-pom` template, can you rebase your branch with that change?

**Review by denis-anisimov — APPROVED** [review]
Looks fine but there are merge conflicts.
Could you please rebase ?

**Comment by stbischof** [comment]
sure, will rebase in next 3 days

**Comment by denis-anisimov** [comment]
There are tests failure in validation.
But I'm not able to decrypt the results. I'm not a project maintainer and know nothing about the validation in the project

**Comment by manolo** [comment]
Those tests randomly fails quite often, I opened an issue https://github.com/vaadin/flow-components/issues/777

**Review by manolo — APPROVED** [review]

**Pull request merged**
