### PR TITLE
refactor!: Drop bower support (14.12)

### PR DESCRIPTION
**Pull request by ZheSun88**
this PR should be considered after flow https://github.com/vaadin/flow/pull/19675

- remove bower pom
- remove bower module declaration
- remove @htmlImport and its import
- remove webjars dependencies
- remove update webjars scripts

### CODE REVIEW

**Comment by ZheSun88** [comment]
bower test has been skipped 
image

**Review by yuriy-fix — CHANGES_REQUESTED** [review]
Blocked by https://github.com/vaadin/flow/pull/19675

**Comment by manolo** [comment]
@yuriy-fix flow PR has been merged and it's now in snapshots can we merge this?

**Review by yuriy-fix — APPROVED** [review]
The remaining changes are available in this PR: https://github.com/vaadin/flow-components/pull/6470

**Comment by manolo** [comment]
There is still a remaining task but it's better to perform in separated PR: remove `*Connector-es6.js`  files

**Pull request merged**
