### PR TITLE
Shim an implementation of `getSubStringLength`

### LINKED ISSUE #5365: X-Axis labels overlapping in svg export
### Description

Vaadin charts with long x-axis labels is overlapping when exported as svg and then downloaded as pdf.  The labels get wrapped in browser but not in the svg. Also when the chart is rendered in small space then the labels are displayed with ellipsis but the generated svg looks much different with respect to labels. 

### Expected outcome

The labels should be wrapped or displayed with ellipsis. 

### Minimal reproducible example
```
public MainView() throws TranscoderException {
		String filepath = "path_to_location/test.pdf";
		Chart chart = new Chart();
		Configuration configuration = chart.getConfiguration();
		configuration.setTitle("");
		configuration.setSubTitle("");
		chart.getConfiguration().getChart().setType(ChartType.COLUMN);

		String months[] = { "January", "February", "March", "April" };
		int survey[][] = { // ETG Base
				{ 8, 0, 7, 0 }, // 164800 obesity
				{ 30, 1, 30, 2 }, // 388100 Hypertension
				{ 37, 0, 22, 2 }, // TQA or pharyngitis
				{ 13, 23, 4, 1 }, // Other skin inflamation
				{ 3, 10, 9, 0 }, // Exposure to infectious disease
		};

		for (int month = 0; month < 4; month++) {
			ListSeries series = new ListSeries();
			for (int num = 0; num < survey.length; num++)
				series.addData(survey[num][month]);
			configuration.addSeries(series);
		}

		XAxis xaxis = new XAxis();
		xaxis.setCategories("164800 obesity", "388100 Hypertension", "TQA or pharyngitis",
				"Other dangerous skin inflamations",
				"Exposure to deadly infectious disease");
		xaxis.setTitle("ETG Base");
		configuration.addxAxis(xaxis);

		Div div = new Div();
		add(div);

		Button downloadButton = new Button("download");
		downloadButton.addClickListener(event -> {
			try (SVGGenerator generator = new SVGGenerator()) {
				ExportOptions exportOptions = new ExportOptions();
				Theme theme = new Theme();

				Legend legend = theme.getLegend();
				legend.setItemMarginTop(50);
				Style titileStyle = theme.getxAxis().getTitle();
				titileStyle.setTop("500px");
				theme.setTitle(titileStyle);
				exportOptions.setTheme(theme);

				String svg = generator.generate(configuration, exportOptions);

				div.getElement().setProperty("innerHTML", svg);

				saveGeneratedSvgAsPdf(svg, filepath);

			} catch (IOException | InterruptedException | TranscoderException ex) {
				// handle exceptions accordingly
			}
		});
		add(downloadButton);
		add(chart);
	}

	public void saveGeneratedSvgAsPdf(String svg, String filePath) throws TranscoderException, FileNotFoundException {

		Transcoder transcoder = new PDFTranscoder();
		TranscoderInput transcoderInput = new TranscoderInput(
				new ByteArrayInputStream(svg.getBytes(StandardCharsets.UTF_8)));
		TranscoderOutput transcoderOutput = new TranscoderOutput(new FileOutputStream(new File(filePath)));
		transcoder.transcode(transcoderInput, transcoderOutput);
	}
```
### Steps to reproduce

1.  Add the above code to any vaadin project (Tested in Version 14 and Version24)
2.  Update the filepath. 
3.  Click on the download button.

### Environment

Vaadin version(s): Tested in V14 with vaadin-charts-flow version 21.0.2 and Vaadin 24 with vaadin-charts-flow version 24.1.4
OS: Windows

### Browsers

Chrome

### PR DESCRIPTION
**Pull request by aroneous**
## Description

Estimate the rendered length of a substring of text in an SVG element. Supports wrapping/truncation of long labels in charts.
Do not consider `<title>` tags in size calculations.

jsdom does not support layout/sizing logic, but some amount of this is required for Highcharts to work correctly. The Highcharts logic to handle wrapping and truncation of long labels relies on the SVG `getSubStringLength` method. Add a shim for this method, which estimates the rendered length of a substring of text. Follow the same basic strategy as used in the existing `getBBox` shim.

When text is truncated, Highcharts inserts a `<title>` element in the SVG with the full text. `getBBox` was considering these elements when computing dimensions. However, these aren't rendered on the screen (they specify tooltips), so this threw off the size calculations and resulted in poor behavior when rendering charts with truncated labels. Stop processing `<title>` elements in `getBBox`.

Update 'expected' SVG for one test where this change led to label truncation (and, therefore, different output).

Fixes #5365

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/contributing/overview
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.
- [x] I have not completed some of the steps above and my pull request can be closed immediately.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by yuriy-fix** [comment]
Thank you, @aroneous, for the great idea to tackle the issue!
We will take care of reviewing the PR and get back to you once it's done.

**Comment by vursen** [comment]
I can confirm that using `0.7` as a constant indeed appears to provide a better result over `0.55`:

**`textLength += usedLength * fontSize * 0.55`**
column-without-title-055

**`textLength += usedLength * fontSize * 0.7`**
column-without-title-070


However, the proposed solution still has some flaws. As you can see on the screenshot above, I extended the "Jul" title and that resulted in an unfortunate layout: the list of cities overlaps the point titles. It's not obvious for me why Highchart produces such a layout. It might be that something else needs to have a shim implementation too, apart from `getSubStringLength`.

For the reference, this is how Highcharts renders the same chart in the browser:

image

**Review by vursen — COMMENTED** [review]
I can confirm that using `0.7` as a constant indeed appears to provide a better result over `0.55`:

**`textLength += usedLength * fontSize * 0.55`**
column-without-title-055

**`textLength += usedLength * fontSize * 0.7`**
column-without-title-070


However, the proposed solution still has some flaws. As you can see on the screenshot above, I extended the "Jul" title and that resulted in an unfortunate layout: the city list overlaps the point titles. I wasn't able to easily figure out why Highchart produces such a layout. It might be that something else also requires a "shim" implementation in addition to `getSubStringLength`.

For the reference, this is how Highcharts renders the same chart in the browser:

image

And this is how Highcharts renders the same chart in SVG without the proposed solution:

column-without-title-070

Given this finding, I'm not sure how safe the solution actually is.

**Comment by aroneous** [comment]
@vursen - hmm, in my testing `getSubStringLength` and `getBBox` were the two methods involved in the sizing and positioning of this area. `getSubStringLength` is required to enable the truncation, and then `getBBox` is called to determine the required space for the labels, whether truncated or not.

I thought I even verified appropriate results for this test chart. I did do my work under Vaadin Charts 21 (as we still need a Java 8-compatible version, and I think that's the most recent version of Vaadin supporting it.) Perhaps you've picked up a newer version of Highcharts which works differently.

It sort of looks like it's reserving an appropriate amount of vertical space to use if the labels were horizontal rather than angled. I believe the version of Highcharts I debugged with measured the rendered size of the labels using getBBox, then did some trigonometry to account for the label rotation. Perhaps they've changed how that's done.

I'll try to find some time to test against the latest version.

**Comment by yuriy-fix** [comment]
Closing as stale. Feel free to request a re-open if there are incoming updates.

**Comment by aroneous** [comment]
It took me awhile, but I've updated the fix to address the problem under newer versions of Vaadin. More details [here](https://github.com/aroneous/flow-components/commit/266d4e4ccc3d6cbfeb3e87ed6c554b1ba3ad7f59). I have updated the source branch of this PR with the changes, and rebased onto latest on main.

Can we reopen this PR?

**Comment by vursen** [comment]
Hey @aroneous! Thanks for your hard work on this issue. Unfortunately, I can't reopen this PR because the branch was force pushed or recreated – Github says that. Could you create a new PR?

**Comment by aroneous** [comment]
@vursen - I have opened #6663 with the latest changes!

**Pull request closed without merging**
