### PR TITLE
chore: remove the scope definition from dependencyManagement (24.0)

### PR DESCRIPTION
**Pull request by ZheSun88**
use DependencyMangement for only version control
remove the scope definition there to avoid further confusion
add <junit> version to dependencymangement

targeting Vaadin 24.0

### CODE REVIEW

**Comment by knoobie** [comment]
@ZheSun88 the same should probably done to the Testbench as well; see https://github.com/vaadin/testbench/issues/1321

**Comment by ZheSun88** [comment]
@knoobie oh, thanks for reminding me.. i will check the testbench dependencies.

**Comment by tomivirkki** [comment]
@ZheSun88 What's the status of this PR? Is it still relevant or could it be closed?

**Comment by ZheSun88** [comment]
@tomivirkki  this change is targeting Vaadin 24.0. same with the PR in  https://github.com/vaadin/platform/pull/3046 . 
so let us keep it for now..

**Review by alvarezguille — APPROVED** [review]

**Pull request merged**
